packages:
  - plugins/basic-design
  - plugins/codiel
  - plugins/codiel/raguel-mcp
  - plugins/chat-history
  - plugins/gh-utility
  - plugins/revelation
  - plugins/pitcrew
  - plugins/raphael
  - plugins/prefetch
  - plugins/guidepost
allowBuilds:
  esbuild: true
